import { requireAdmin } from "../lib/auth/session.ts";
import { operationalStaffRoles } from "../lib/auth/operational-staff.ts";
import { weekRange } from "../lib/staff-control/calendar.ts";
import { calculateBonus, freezeConfig, rankRecommendations, type BonusMetrics, type BonusRecommendation, type BonusSettings, type BonusTier } from "../lib/staff-control/bonus.ts";
import { validateBonusSettings, validateBonusTiers } from "../lib/staff-control/bonus-settings.ts";
import { createSupabaseAdminClient } from "../lib/supabase/admin.ts";
import { StaffControlError } from "./staff-control.ts";
import { aggregateWeeklyMetrics as aggregateWeeklyMetricsDomain, mapBonusSettingsRow as mapBonusSettingsRowDomain, mapBonusTierRow as mapBonusTierRowDomain, type BonusAggregationSource } from "../lib/staff-control/bonus-aggregation.ts";

const DATE = /^\d{4}-\d{2}-\d{2}$/;
const REVIEW_SEPARATOR = "||";
const timeZone = () => process.env.APP_TIMEZONE && process.env.APP_TIMEZONE !== "undefined" ? process.env.APP_TIMEZONE : "America/Monterrey";
const error = (message: string): never => { throw new StaffControlError("INTERNAL_ERROR", message); };
const validation = (message: string): never => { throw new StaffControlError("VALIDATION_ERROR", message); };
const conflict = (message: string): never => { throw new StaffControlError("CONFLICT", message); };
const dateOnly = (value: unknown): string => { if (typeof value !== "string" || !DATE.test(value)) validation("Semana inválida"); const parsed = new Date(`${value}T12:00:00Z`); if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== value) validation("Semana inválida"); return value as string; };
const monday = (value: unknown): string => { const date = dateOnly(value); if (new Date(`${date}T12:00:00Z`).getUTCDay() !== 1) validation("La semana debe iniciar en lunes"); return date; };
const nextDate = (date: string, days: number) => { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); };

export type BonusAudit = { at: string | null; by: string | null; byName: string | null; reason: string | null };
export type BonusSimulationResult = { profileId: string; rpName: string; rank: number; recommendation: BonusRecommendation & { reviewResolved: boolean; reviewResolution: BonusAudit; override: BonusAudit & { amount: number | null }; finalAmount: number | null; effectiveAmount: number } };
export type BonusSimulation = { runId: string | null; weekStart: string; weekEnd: string; status: "draft" | "finalized"; finalizedAt: string | null; finalizedBy: string | null; finalizedByName: string | null; currentWeek: boolean; settings: BonusSettings; tiers: BonusTier[]; summary: { evaluated: number; averageScore: number; estimatedTotal: number; reviewRequired: number; reviewResolved: number; overrides: number; finalTotal: number }; top3: BonusSimulationResult[]; results: BonusSimulationResult[] };
export type BonusRunHistoryItem = { runId: string; weekStart: string; weekEnd: string; status: "draft" | "finalized"; finalizedAt: string | null; finalizedByName: string | null; total: number; evaluated: number };

async function admin() { try { return await requireAdmin(); } catch (cause) { const message = cause instanceof Error ? cause.message : ""; throw new StaffControlError(message === "Forbidden" ? "FORBIDDEN" : "UNAUTHORIZED", message === "Forbidden" ? "No tienes permisos administrativos" : "No autorizado"); } }
async function loadSettings(client: ReturnType<typeof createSupabaseAdminClient>) { const [settingsResult, tiersResult] = await Promise.all([client.from("bonus_settings").select("*").eq("id", true).single(), client.from("bonus_tiers").select("position, min_score, max_score, amount").order("position", { ascending: true })]); if (settingsResult.error || tiersResult.error || !settingsResult.data) error("No se pudo cargar la configuración de bonos"); const settings = mapBonusSettingsRowDomain(settingsResult.data); const tiers = validateBonusTiers((tiersResult.data ?? []).map(mapBonusTierRowDomain)); return { settings, tiers }; }
export async function getBonusSettings() { await admin(); return loadSettings(createSupabaseAdminClient()); }

export async function updateBonusSettings(input: { settings?: unknown; tiers?: unknown }) { const actor = await admin(); if (input.settings === undefined || input.tiers === undefined) validation("Configuración de bonos inválida"); const settings = validateBonusSettings(input.settings); const tiers = validateBonusTiers(input.tiers); const client = createSupabaseAdminClient(); const result = await client.rpc("save_bonus_settings", { p_actor: actor.id, p_settings: settings, p_tiers: tiers.map((tier) => ({ position: tier.position, min_score: tier.minScore, max_score: tier.maxScore, amount: tier.amount })) }); if (result.error) { if (process.env.NODE_ENV !== "production" && result.error.message.includes("DELETE requires a WHERE clause")) { const persisted = await client.from("bonus_settings").update({ weekly_goal_minutes: settings.weeklyGoalMinutes, peak_start: settings.peakStart, peak_end: settings.peakEnd, active_day_minimum_minutes: settings.activeDayMinimumMinutes, peak_target_minutes: settings.peakTargetMinutes, normal_target_minutes: settings.normalTargetMinutes, kits_target: settings.kitsTarget, active_days_target: settings.activeDaysTarget, peak_weight: settings.peakWeight, kits_weight: settings.kitsWeight, normal_weight: settings.normalWeight, consistency_weight: settings.consistencyWeight, inactivity_alert_days: settings.inactivityAlertDays, warns_per_strike: settings.warnsPerStrike, critical_strikes: settings.criticalStrikes, updated_by: actor.id }).eq("id", true); const cleared = await client.from("bonus_tiers").delete().gte("position", 0); const inserted = await client.from("bonus_tiers").insert(tiers.map((tier) => ({ position: tier.position, min_score: tier.minScore, max_score: tier.maxScore, amount: tier.amount }))); if (persisted.error || cleared.error || inserted.error) validation("No se pudo guardar la configuración de bonos"); } else validation("No se pudo guardar la configuración de bonos"); } return loadSettings(createSupabaseAdminClient()); }

function parseReviewReason(raw: unknown): { codes: Array<"WEEKLY_GOAL_NOT_MET" | "JUSTIFIED_ABSENCE">; resolutionReason: string | null } { const value = typeof raw === "string" ? raw : ""; const [codePart, resolutionPart] = value.split(REVIEW_SEPARATOR, 2); const codes = codePart.split(",").filter((item): item is "WEEKLY_GOAL_NOT_MET" | "JUSTIFIED_ABSENCE" => item === "WEEKLY_GOAL_NOT_MET" || item === "JUSTIFIED_ABSENCE"); return { codes, resolutionReason: resolutionPart?.trim() || null }; }
function encodeReviewReason(codes: string[], resolutionReason?: string | null) { if (!codes.length && !resolutionReason?.trim()) return null; return `${codes.join(",")}${resolutionReason ? `${REVIEW_SEPARATOR}${resolutionReason.trim()}` : ""}`; }
function namesById(profiles: Array<{ id: string; rp_name: string }>) { return new Map(profiles.map((profile) => [profile.id, profile.rp_name])); }
function resultFromRow(row: Record<string, unknown>, rpName: string, names: Map<string, string>): BonusSimulationResult {
  const parsed = parseReviewReason(row.review_reason);
  const metrics: BonusMetrics = { weeklyMinutes: Number(row.weekly_minutes ?? 0), peakMinutes: Number(row.peak_minutes ?? 0), normalMinutes: Number(row.normal_minutes ?? 0), kits: Number(row.kits ?? 0), activeDays: Number(row.active_days ?? 0), activeFineTotal: Number(row.fine_total ?? 0), hasRelevantJustifiedAbsence: parsed.codes.includes("JUSTIFIED_ABSENCE") };
  const reviewAt = row.review_resolved_at ? String(row.review_resolved_at) : null;
  const reviewBy = row.review_resolved_by ? String(row.review_resolved_by) : null;
  const overrideAt = row.override_at ? String(row.override_at) : null;
  const overrideBy = row.override_by ? String(row.override_by) : null;
  const overrideAmount = row.override_amount === null || row.override_amount === undefined ? null : Number(row.override_amount);
  const recommendation = { metrics, components: { peak: Number(row.peak_score ?? 0), kits: Number(row.kits_score ?? 0), normal: Number(row.normal_score ?? 0), consistency: Number(row.consistency_score ?? 0) }, score: Number(row.total_score ?? 0), displayScore: Math.round(Number(row.total_score ?? 0)), baseAmount: Number(row.base_amount ?? 0), fineTotal: Number(row.fine_total ?? 0), recommendedFinal: Number(row.recommended_final_amount ?? 0), goalMet: !parsed.codes.includes("WEEKLY_GOAL_NOT_MET"), reviewRequired: Boolean(row.review_required), reviewReasons: parsed.codes, reviewResolved: Boolean(reviewAt), reviewResolution: { at: reviewAt, by: reviewBy, byName: reviewBy ? names.get(reviewBy) ?? null : null, reason: parsed.resolutionReason }, override: { at: overrideAt, by: overrideBy, byName: overrideBy ? names.get(overrideBy) ?? null : null, reason: row.override_reason ? String(row.override_reason) : null, amount: overrideAmount }, finalAmount: row.final_amount === null || row.final_amount === undefined ? null : Number(row.final_amount), effectiveAmount: overrideAmount ?? (row.final_amount === null || row.final_amount === undefined ? Number(row.recommended_final_amount ?? 0) : Number(row.final_amount)) };
  return { profileId: String(row.profile_id), rpName, rank: 0, recommendation };
}
function response(results: BonusSimulationResult[], run: { id: string | null; status: "draft" | "finalized"; finalized_at?: string | null; finalized_by?: string | null }, weekStart: string, weekEnd: string, currentWeek: boolean, settings: BonusSettings, tiers: BonusTier[], names: Map<string, string>): BonusSimulation { const ranked = results.map((result, index) => ({ ...result, rank: index + 1 })); const finalized = run.status === "finalized"; const averageScore = ranked.length ? Math.round((ranked.reduce((sum, item) => sum + item.recommendation.score, 0) / ranked.length) * 100) / 100 : 0; return { runId: run.id, weekStart, weekEnd, status: run.status, finalizedAt: run.finalized_at ?? null, finalizedBy: run.finalized_by ?? null, finalizedByName: run.finalized_by ? names.get(run.finalized_by) ?? null : null, currentWeek, settings, tiers, summary: { evaluated: ranked.length, averageScore, estimatedTotal: ranked.reduce((sum, item) => sum + item.recommendation.recommendedFinal, 0), reviewRequired: ranked.filter((item) => item.recommendation.reviewRequired && !item.recommendation.reviewResolved).length, reviewResolved: ranked.filter((item) => item.recommendation.reviewRequired && item.recommendation.reviewResolved).length, overrides: ranked.filter((item) => item.recommendation.override.amount !== null).length, finalTotal: finalized ? ranked.reduce((sum, item) => sum + item.recommendation.effectiveAmount, 0) : 0 }, top3: ranked.slice(0, 3), results: ranked }; }

export async function simulateWeek(input: { weekStart?: unknown }, now = new Date()): Promise<BonusSimulation> {
  const actor = await admin(); const weekStart = monday(input.weekStart); const zone = timeZone(); const range = weekRange(new Date(`${weekStart}T12:00:00Z`), zone); const weekEnd = nextDate(weekStart, 6); const client = createSupabaseAdminClient();
  const [profilesResult, shiftsResult, deliveriesResult, finesResult, absencesResult, config, runResult] = await Promise.all([client.from("profiles").select("id, rp_name, role, active").in("role", [...operationalStaffRoles]).eq("active", true), client.from("ems_shifts").select("profile_id, started_at, ended_at").lt("started_at", range.end.toISOString()).or(`ended_at.is.null,ended_at.gt.${range.start.toISOString()}`), client.from("deliveries").select("delivered_by, occurred_at").gte("occurred_at", range.start.toISOString()).lt("occurred_at", range.end.toISOString()), client.from("disciplinary_actions").select("profile_id, fine_amount").eq("type", "fine").eq("applies_to_week", weekStart).is("voided_at", null), client.from("justified_absences").select("profile_id, starts_on, ends_on").lte("starts_on", weekEnd).gte("ends_on", weekStart).is("voided_at", null), loadSettings(client), client.from("bonus_runs").select("id, status, config_snapshot, finalized_at, finalized_by").eq("week_start", weekStart).maybeSingle()]);
  if (profilesResult.error || shiftsResult.error || deliveriesResult.error || finesResult.error || absencesResult.error || runResult.error) error("No se pudo cargar la simulación semanal");
  const profiles = (profilesResult.data ?? []) as Array<{ id: string; rp_name: string; role: "admin" | "ems"; active: boolean }>; const names = namesById(profiles); const run = runResult.data;
  if (run?.status === "finalized") { const resultsResult = await client.from("bonus_results").select("*").eq("run_id", run.id).order("total_score", { ascending: false }).order("peak_minutes", { ascending: false }).order("profile_id", { ascending: true }); if (resultsResult.error) error("No se pudo cargar la simulación finalizada"); const results = (resultsResult.data ?? []).map((row) => resultFromRow(row as Record<string, unknown>, names.get(String(row.profile_id)) ?? "EMS", names)); const frozen = snapshotConfig(run.config_snapshot, config); return response(results, run, weekStart, weekEnd, range.start <= now && now < range.end, frozen.settings, frozen.tiers, names); }
  const source: BonusAggregationSource = { profiles, shifts: (shiftsResult.data ?? []) as BonusAggregationSource["shifts"], deliveries: (deliveriesResult.data ?? []) as BonusAggregationSource["deliveries"], fines: (finesResult.data ?? []) as BonusAggregationSource["fines"], absences: (absencesResult.data ?? []) as BonusAggregationSource["absences"] };
  const metrics = aggregateWeeklyMetricsDomain(source, config.settings, weekStart, zone, now); const calculated = metrics.map((row) => ({ profileId: row.profileId, rpName: row.rpName, recommendation: calculateBonus(row.metrics, config.settings, config.tiers) })); const ranked = rankRecommendations(calculated); let runId = run?.id ? String(run.id) : null;
  if (!runId) { const inserted = await client.from("bonus_runs").insert({ week_start: weekStart, status: "draft", config_snapshot: freezeConfig(config.settings, config.tiers), created_by: actor.id }).select("id, status, finalized_at, finalized_by").single(); if (inserted.error || !inserted.data) error("No se pudo crear el borrador semanal"); const insertedData = inserted.data as { id: string }; runId = String(insertedData.id); } else { const updated = await client.from("bonus_runs").update({ config_snapshot: freezeConfig(config.settings, config.tiers) }).eq("id", runId).eq("status", "draft"); if (updated.error) error("No se pudo actualizar el borrador semanal"); }
  const existingResult = runId ? await client.from("bonus_results").select("profile_id, review_reason, review_resolved_at, review_resolved_by, override_amount, override_reason, override_by, override_at").eq("run_id", runId) : { data: [], error: null }; if (existingResult.error) error("No se pudo cargar el borrador semanal"); const previous = new Map((existingResult.data ?? []).map((row) => [String(row.profile_id), row]));
  const rows = ranked.map((entry) => { const prior = previous.get(entry.profileId); return { run_id: runId, profile_id: entry.profileId, weekly_minutes: entry.recommendation.metrics.weeklyMinutes, peak_minutes: entry.recommendation.metrics.peakMinutes, normal_minutes: entry.recommendation.metrics.normalMinutes, kits: entry.recommendation.metrics.kits, active_days: entry.recommendation.metrics.activeDays, peak_score: entry.recommendation.components.peak, kits_score: entry.recommendation.components.kits, normal_score: entry.recommendation.components.normal, consistency_score: entry.recommendation.components.consistency, total_score: entry.recommendation.score, base_amount: entry.recommendation.baseAmount, fine_total: entry.recommendation.fineTotal, recommended_final_amount: entry.recommendation.recommendedFinal, review_required: entry.recommendation.reviewRequired, review_reason: prior?.review_reason ?? encodeReviewReason(entry.recommendation.reviewReasons), review_resolved_at: prior?.review_resolved_at ?? null, review_resolved_by: prior?.review_resolved_by ?? null, override_amount: prior?.override_amount ?? null, override_reason: prior?.override_reason ?? null, override_by: prior?.override_by ?? null, override_at: prior?.override_at ?? null }; });
  if (rows.length) { const saved = await client.from("bonus_results").upsert(rows, { onConflict: "run_id,profile_id" }); if (saved.error) error("No se pudo guardar el borrador semanal"); }
  const results = rows.map((row) => resultFromRow(row as unknown as Record<string, unknown>, names.get(row.profile_id) ?? "EMS", names)); return response(results, { id: runId, status: "draft" }, weekStart, weekEnd, range.start <= now && now < range.end, config.settings, config.tiers, names);
}

function snapshotConfig(value: unknown, fallback: { settings: BonusSettings; tiers: BonusTier[] }) { if (!value || typeof value !== "object" || Array.isArray(value)) return fallback; const record = value as Record<string, unknown>; try { return { settings: validateBonusSettings(record.settings), tiers: validateBonusTiers(record.tiers) }; } catch { return fallback; } }
async function loadDraftTarget(weekValue: unknown, profileValue: unknown) { const weekStart = monday(weekValue); if (typeof profileValue !== "string") validation("EMS inválido"); const client = createSupabaseAdminClient(); const run = await client.from("bonus_runs").select("id, status").eq("week_start", weekStart).maybeSingle(); if (run.error) error("No se pudo cargar el borrador semanal"); if (!run.data) throw new StaffControlError("NOT_FOUND", "No existe simulación para esta semana"); if (run.data.status !== "draft") conflict("La semana ya está finalizada y es inmutable"); const result = await client.from("bonus_results").select("*").eq("run_id", run.data.id).eq("profile_id", profileValue).maybeSingle(); if (result.error) error("No se pudo cargar el resultado semanal"); if (!result.data) throw new StaffControlError("NOT_FOUND", "Resultado EMS no encontrado"); return { client, weekStart, runId: String(run.data.id), row: result.data as Record<string, unknown> }; }

export async function resolveBonusReview(input: { weekStart?: unknown; profileId?: unknown; reason?: unknown }) { const actor = await admin(); const reason = typeof input.reason === "string" ? input.reason.trim() : ""; if (!reason) validation("Motivo de revisión requerido"); const target = await loadDraftTarget(input.weekStart, input.profileId); const parsed = parseReviewReason(target.row.review_reason); if (!target.row.review_required || target.row.review_resolved_at) conflict("Esta revisión ya fue resuelta"); const updated = await target.client.from("bonus_results").update({ review_resolved_at: new Date().toISOString(), review_resolved_by: actor.id, review_reason: encodeReviewReason(parsed.codes, reason) }).eq("id", target.row.id).eq("run_id", target.runId).is("review_resolved_at", null).select("*").maybeSingle(); if (updated.error) error("No se pudo resolver la revisión"); if (!updated.data) conflict("Esta revisión ya fue resuelta"); return getBonusRun(target.weekStart); }
export async function overrideBonusResult(input: { weekStart?: unknown; profileId?: unknown; amount?: unknown; reason?: unknown }) { const actor = await admin(); const reason = typeof input.reason === "string" ? input.reason.trim() : ""; if (!reason) validation("Motivo del ajuste requerido"); if (!Number.isInteger(input.amount) || Number(input.amount) < 0) validation("El bono debe ser un entero mayor o igual a cero"); const target = await loadDraftTarget(input.weekStart, input.profileId); const parsed = parseReviewReason(target.row.review_reason); const patch: Record<string, unknown> = { override_amount: Number(input.amount), override_reason: reason, override_by: actor.id, override_at: new Date().toISOString() }; if (target.row.review_required && !target.row.review_resolved_at) { patch.review_resolved_at = new Date().toISOString(); patch.review_resolved_by = actor.id; patch.review_reason = encodeReviewReason(parsed.codes, `Ajuste: ${reason}`); } const updated = await target.client.from("bonus_results").update(patch).eq("id", target.row.id).eq("run_id", target.runId).is("override_at", null).select("*").maybeSingle(); if (updated.error) error("No se pudo guardar el ajuste"); if (!updated.data) conflict("Este resultado ya tiene un ajuste"); return getBonusRun(target.weekStart); }
export async function finalizeBonusRun(input: { weekStart?: unknown }) { const actor = await admin(); const weekStart = monday(input.weekStart); const client = createSupabaseAdminClient(); const run = await client.from("bonus_runs").select("id, status").eq("week_start", weekStart).maybeSingle(); if (run.error) error("No se pudo cargar la semana"); if (!run.data) throw new StaffControlError("NOT_FOUND", "No existe simulación para esta semana"); if (run.data.status !== "draft") conflict("La semana ya está finalizada"); const pending = await client.from("bonus_results").select("id", { count: "exact", head: true }).eq("run_id", run.data.id).eq("review_required", true).is("review_resolved_at", null); if (pending.error) error("No se pudo validar las revisiones"); if ((pending.count ?? 0) > 0) conflict(`Hay ${pending.count} revisiones pendientes.`); const result = await client.rpc("finalize_bonus_run", { p_run_id: run.data.id, p_actor: actor.id }); if (result.error) { if (result.error.message.toLowerCase().includes("revisiones")) conflict("Hay revisiones pendientes."); if (result.error.message.toLowerCase().includes("finalizable")) conflict("La semana ya está finalizada."); error("No se pudo finalizar la semana"); } return getBonusRun(weekStart); }

export async function getBonusRun(weekValue: unknown) { const weekStart = monday(weekValue); const client = createSupabaseAdminClient(); const run = await client.from("bonus_runs").select("id, status, config_snapshot, finalized_at, finalized_by").eq("week_start", weekStart).maybeSingle(); if (run.error) error("No se pudo cargar la semana"); if (!run.data) throw new StaffControlError("NOT_FOUND", "No existe simulación para esta semana"); const [results, profiles] = await Promise.all([client.from("bonus_results").select("*").eq("run_id", run.data.id).order("total_score", { ascending: false }).order("peak_minutes", { ascending: false }).order("profile_id", { ascending: true }), client.from("profiles").select("id, rp_name")]); if (results.error || profiles.error) error("No se pudo cargar la semana"); const names = namesById((profiles.data ?? []) as Array<{ id: string; rp_name: string }>); const settings = snapshotConfig(run.data.config_snapshot, await loadSettings(client)); const mapped = (results.data ?? []).map((row) => resultFromRow(row as Record<string, unknown>, names.get(String(row.profile_id)) ?? "EMS", names)); return response(mapped, run.data, weekStart, nextDate(weekStart, 6), weekRange(new Date(), timeZone()).start.toISOString().slice(0, 10) === weekStart && run.data.status === "draft", settings.settings, settings.tiers, names); }

export async function listBonusRuns() { await admin(); const client = createSupabaseAdminClient(); const runs = await client.from("bonus_runs").select("id, week_start, status, finalized_at, finalized_by").order("week_start", { ascending: false }).limit(20); if (runs.error) error("No se pudo cargar el histórico de bonos"); const runIds = (runs.data ?? []).map((run) => run.id); const results = runIds.length ? await client.from("bonus_results").select("run_id, final_amount, recommended_final_amount").in("run_id", runIds) : { data: [], error: null }; if (results.error) error("No se pudo cargar el histórico de bonos"); const names = namesById(((await client.from("profiles").select("id, rp_name")).data ?? []) as Array<{ id: string; rp_name: string }>); return (runs.data ?? []).map((run) => { const rows = (results.data ?? []).filter((row) => row.run_id === run.id); return { runId: String(run.id), weekStart: String(run.week_start), weekEnd: nextDate(String(run.week_start), 6), status: run.status as "draft" | "finalized", finalizedAt: run.finalized_at, finalizedByName: run.finalized_by ? names.get(String(run.finalized_by)) ?? null : null, total: rows.reduce((sum, row) => sum + Number(row.final_amount ?? row.recommended_final_amount ?? 0), 0), evaluated: rows.length }; }); }
export async function getStaffBonusHistory(profileValue: unknown, pageValue: unknown = 1) { await admin(); if (typeof profileValue !== "string") validation("EMS inválido"); const page = Number(pageValue); if (!Number.isInteger(page) || page < 1) validation("Página inválida"); const client = createSupabaseAdminClient(); const profile = await client.from("profiles").select("id").eq("id", profileValue).maybeSingle(); if (profile.error) error("No se pudo cargar el histórico del EMS"); if (!profile.data) throw new StaffControlError("NOT_FOUND", "EMS no encontrado"); const runs = await client.from("bonus_runs").select("id, week_start, status, finalized_at").order("week_start", { ascending: false }).limit(20); if (runs.error) error("No se pudo cargar el histórico del EMS"); const ids = (runs.data ?? []).map((run) => run.id); const results = ids.length ? await client.from("bonus_results").select("run_id, total_score, final_amount, recommended_final_amount, override_amount, fine_total").eq("profile_id", profileValue).in("run_id", ids) : { data: [], error: null }; if (results.error) error("No se pudo cargar el histórico del EMS"); const items = (runs.data ?? []).map((run) => ({ runId: String(run.id), weekStart: String(run.week_start), weekEnd: nextDate(String(run.week_start), 6), status: run.status as "draft" | "finalized", finalizedAt: run.finalized_at, score: Number(results.data?.find((row) => row.run_id === run.id)?.total_score ?? 0), finalAmount: results.data?.find((row) => row.run_id === run.id)?.final_amount ?? results.data?.find((row) => row.run_id === run.id)?.recommended_final_amount ?? 0, hasOverride: results.data?.some((row) => row.run_id === run.id && row.override_amount !== null) ?? false })).filter((item) => item.score || item.finalAmount); const pageSize = 10; return { items: items.slice((page - 1) * pageSize, page * pageSize), page, pageSize, total: items.length, totalPages: Math.max(1, Math.ceil(items.length / pageSize)) }; }
export type StaffBonusHistoryItem = { runId: string; weekStart: string; weekEnd: string; status: "draft" | "finalized"; finalizedAt: string | null; score: number; finalAmount: number; hasOverride: boolean; configSnapshot?: unknown; metrics: { weeklyMinutes: number; peakMinutes: number; normalMinutes: number; kits: number; activeDays: number }; components: { peak: number; kits: number; normal: number; consistency: number }; baseAmount: number; fineTotal: number; recommendedFinal: number; reviewRequired: boolean; reviewResolvedAt: string | null; reviewResolvedByName: string | null; reviewReason: string | null; overrideAmount: number | null; overrideReason: string | null; overrideAt: string | null; overrideByName: string | null };
export type StaffBonusHistory = { items: StaffBonusHistoryItem[]; page: number; pageSize: number; total: number; totalPages: number };

export async function getStaffBonusHistoryDetail(profileValue: unknown, pageValue: unknown = 1): Promise<StaffBonusHistory> {
  const base = await getStaffBonusHistory(profileValue, pageValue); const ids = base.items.map((item) => item.runId); if (!ids.length) return { ...base, items: [] }; const client = createSupabaseAdminClient();
  const [runs, results] = await Promise.all([client.from("bonus_runs").select("id, config_snapshot").in("id", ids), client.from("bonus_results").select("run_id, weekly_minutes, peak_minutes, normal_minutes, kits, active_days, peak_score, kits_score, normal_score, consistency_score, base_amount, fine_total, recommended_final_amount, final_amount, review_required, review_resolved_at, review_resolved_by, review_reason, override_amount, override_reason, override_by, override_at").eq("profile_id", profileValue).in("run_id", ids)]); if (runs.error || results.error) error("No se pudo cargar el detalle histórico del EMS");
  const rows = (results.data ?? []) as Array<Record<string, unknown>>; const actorIds = [...new Set(rows.flatMap((row) => [row.review_resolved_by, row.override_by].filter((id): id is string => typeof id === "string")))]; const actors = actorIds.length ? await client.from("profiles").select("id, rp_name").in("id", actorIds) : { data: [], error: null }; if (actors.error) error("No se pudo cargar la auditoría del EMS"); const names = new Map((actors.data ?? []).map((actor) => [String(actor.id), String(actor.rp_name)])); const runSnapshots = new Map((runs.data ?? []).map((run) => [String(run.id), run.config_snapshot]));
  return { ...base, items: base.items.map((item) => { const row = rows.find((candidate) => String(candidate.run_id) === item.runId); if (!row) return { ...item, configSnapshot: undefined, metrics: { weeklyMinutes: 0, peakMinutes: 0, normalMinutes: 0, kits: 0, activeDays: 0 }, components: { peak: 0, kits: 0, normal: 0, consistency: 0 }, baseAmount: 0, fineTotal: 0, recommendedFinal: item.finalAmount, reviewRequired: false, reviewResolvedAt: null, reviewResolvedByName: null, reviewReason: null, overrideAmount: null, overrideReason: null, overrideAt: null, overrideByName: null }; return { ...item, configSnapshot: runSnapshots.get(item.runId), metrics: { weeklyMinutes: Number(row.weekly_minutes ?? 0), peakMinutes: Number(row.peak_minutes ?? 0), normalMinutes: Number(row.normal_minutes ?? 0), kits: Number(row.kits ?? 0), activeDays: Number(row.active_days ?? 0) }, components: { peak: Number(row.peak_score ?? 0), kits: Number(row.kits_score ?? 0), normal: Number(row.normal_score ?? 0), consistency: Number(row.consistency_score ?? 0) }, baseAmount: Number(row.base_amount ?? 0), fineTotal: Number(row.fine_total ?? 0), recommendedFinal: Number(row.recommended_final_amount ?? 0), finalAmount: Number(row.final_amount ?? row.recommended_final_amount ?? 0), reviewRequired: Boolean(row.review_required), reviewResolvedAt: row.review_resolved_at ? String(row.review_resolved_at) : null, reviewResolvedByName: row.review_resolved_by ? names.get(String(row.review_resolved_by)) ?? null : null, reviewReason: row.review_reason ? String(row.review_reason) : null, overrideAmount: row.override_amount === null || row.override_amount === undefined ? null : Number(row.override_amount), overrideReason: row.override_reason ? String(row.override_reason) : null, overrideAt: row.override_at ? String(row.override_at) : null, overrideByName: row.override_by ? names.get(String(row.override_by)) ?? null : null }; }) };
}
