import "server-only";

import { requireAdmin } from "../lib/auth/session.ts";
import { operationalStaffRoles } from "../lib/auth/operational-staff.ts";
import { getAnalyticsRange, overlapMilliseconds, type AnalyticsRangeKey } from "../lib/shifts/time.ts";
import { createSupabaseAdminClient } from "../lib/supabase/admin.ts";
import type { Shift } from "./shifts.ts";

type Delivery = { id: string; delivered_by: string; type: "civil" | "police"; quantity_label: string; occurred_at: string; people?: { display_name: string } | null };
type Operator = { id: string; username: string; rp_name: string; role: "admin" | "ems"; active: boolean };
export type PerformanceFilters = { range?: string; from?: string; to?: string; page?: string };
function rangeFor(filters: PerformanceFilters) { const allowed: AnalyticsRangeKey[] = ["today", "7d", "30d", "month", "all", "custom"]; return getAnalyticsRange(allowed.includes(filters.range as AnalyticsRangeKey) ? filters.range as AnalyticsRangeKey : "today", filters); }
function totals(profileId: string, shifts: Shift[], deliveries: Delivery[], start: Date | null, end: Date) { const relevantShifts = shifts.filter((shift) => shift.profile_id === profileId); const hours = start ? relevantShifts.reduce((sum, shift) => sum + overlapMilliseconds(shift.started_at, shift.ended_at, start, end), 0) : relevantShifts.reduce((sum, shift) => sum + Math.max(0, Math.min(new Date(shift.ended_at ?? end).getTime(), end.getTime()) - new Date(shift.started_at).getTime()), 0); const relevantDeliveries = deliveries.filter((delivery) => delivery.delivered_by === profileId); const civil = relevantDeliveries.filter((delivery) => delivery.type === "civil").length; const police = relevantDeliveries.length - civil; const breakdown: Record<string, number> = {}; for (const delivery of relevantDeliveries) breakdown[delivery.quantity_label] = (breakdown[delivery.quantity_label] ?? 0) + 1; return { hoursMilliseconds: hours, deliveries: relevantDeliveries.length, civil, police, breakdown }; }
async function data(filters: PerformanceFilters) { const range = rangeFor(filters); const client = createSupabaseAdminClient(); let deliveryQuery = client.from("deliveries").select("id, delivered_by, type, quantity_label, occurred_at, people(display_name)").lt("occurred_at", range.end.toISOString()); if (range.start) deliveryQuery = deliveryQuery.gte("occurred_at", range.start.toISOString()); const [profiles, shifts, deliveries] = await Promise.all([client.from("profiles").select("id, username, rp_name, role, active").in("role", [...operationalStaffRoles]).order("rp_name"), client.from("ems_shifts").select("*").lt("started_at", range.end.toISOString()), deliveryQuery]); if (profiles.error || shifts.error || deliveries.error) throw new Error("No se pudieron calcular las analíticas"); return { range, profiles: (profiles.data ?? []) as Operator[], shifts: (shifts.data ?? []) as Shift[], deliveries: (deliveries.data ?? []) as unknown as Delivery[] }; }
export async function listEmsPerformance(filters: PerformanceFilters) { await requireAdmin(); const result = await data(filters); return { range: { label: result.range.label, start: result.range.start?.toISOString() ?? null, end: result.range.end.toISOString() }, items: result.profiles.map((profile) => ({ profile, ...totals(profile.id, result.shifts, result.deliveries, result.range.start, result.range.end) })) }; }
export async function getEmsPerformance(profileId: string, filters: PerformanceFilters) { await requireAdmin(); const result = await data(filters); const profile = result.profiles.find((item) => item.id === profileId); if (!profile) throw new Error("EMS no encontrado"); const page = Math.max(1, Number(filters.page) || 1); const limit = 25; const deliveryItems = result.deliveries.filter((item) => item.delivered_by === profileId).sort((a, b) => b.occurred_at.localeCompare(a.occurred_at)); return { range: { label: result.range.label, start: result.range.start?.toISOString() ?? null, end: result.range.end.toISOString() }, profile, metrics: totals(profile.id, result.shifts, result.deliveries, result.range.start, result.range.end), shifts: result.shifts.filter((item) => item.profile_id === profileId).sort((a, b) => b.started_at.localeCompare(a.started_at)), deliveries: { items: deliveryItems.slice((page - 1) * limit, page * limit), page, count: deliveryItems.length, limit } }; }
