import "server-only";

import { requireActiveProfile, requireAdmin } from "../lib/auth/session.ts";
import { buildShiftCloseContent, buildShiftOpenContent, decryptWebhook, encryptWebhook, getWebhookEncryptionKey, isDiscordWebhookUrl } from "../lib/discord/shift-webhook.ts";
import { sendDiscordWebhook } from "../lib/discord/webhook.ts";
import { formatDateTime } from "../lib/time/date.ts";
import { formatDuration, shiftDurationMilliseconds } from "../lib/shifts/time.ts";
import { createSupabaseAdminClient } from "../lib/supabase/admin.ts";

export type Shift = { id: string; profile_id: string; started_at: string; ended_at: string | null; created_at: string; discord_open_status?: string | null; discord_open_error?: string | null; discord_close_status?: string | null; discord_close_error?: string | null };
type StoredWebhook = { profile_id: string; iv: string; ciphertext: string; auth_tag: string };
export class ShiftConflictError extends Error { constructor(message: string) { super(message); this.name = "ShiftConflictError"; } }
export class WebhookConfigurationError extends Error { constructor(message: string) { super(message); this.name = "WebhookConfigurationError"; } }
function safeError(error: unknown) { return (error instanceof Error ? error.message : "No se pudo notificar a Discord").replace(/https?:\/\/\S+/gi, "[webhook]").slice(0, 240); }

async function webhookFor(profileId: string) { const result = await createSupabaseAdminClient().from("ems_discord_webhooks").select("profile_id, iv, ciphertext, auth_tag").eq("profile_id", profileId).maybeSingle<StoredWebhook>(); if (!result.data) return null; return decryptWebhook(result.data, getWebhookEncryptionKey().toString("base64")); }
async function notify(shift: Shift, profileName: string, kind: "open" | "close") {
  let webhook: string | null; try { webhook = await webhookFor(shift.profile_id); } catch { return { status: "failed", error: "No se pudo notificar a Discord por configuración del servidor." } as const; } if (!webhook) return { status: "not_configured", error: "No tienes un webhook de Discord configurado." } as const;
  const content = kind === "open" ? buildShiftOpenContent(profileName, formatDateTime(shift.started_at)) : buildShiftCloseContent(profileName, formatDateTime(shift.started_at), formatDateTime(shift.ended_at!), formatDuration(shiftDurationMilliseconds(shift.started_at, shift.ended_at!)));
  try { await sendDiscordWebhook({ webhookUrl: webhook, content, attachments: [] }); return { status: "sent", error: null } as const; } catch (error) { return { status: "failed", error: safeError(error) } as const; }
}
async function recordNotification(shift: Shift, profileName: string, kind: "open" | "close") { const result = await notify(shift, profileName, kind); const fields = kind === "open" ? { discord_open_status: result.status, discord_open_error: result.error } : { discord_close_status: result.status, discord_close_error: result.error }; await createSupabaseAdminClient().from("ems_shifts").update(fields).eq("id", shift.id); return result; }

export async function getCurrentShift() { const profile = await requireActiveProfile(); const result = await createSupabaseAdminClient().from("ems_shifts").select("*").eq("profile_id", profile.id).is("ended_at", null).maybeSingle<Shift>(); if (result.error) throw new Error("No se pudo consultar la bitácora"); return result.data; }
export async function openShift() { const profile = await requireActiveProfile(); const client = createSupabaseAdminClient(); const existing = await client.from("ems_shifts").select("id").eq("profile_id", profile.id).is("ended_at", null).maybeSingle(); if (existing.data) throw new ShiftConflictError("Ya tienes una bitácora abierta."); const created = await client.from("ems_shifts").insert({ profile_id: profile.id, started_at: new Date().toISOString() }).select("*").single<Shift>(); if (created.error?.code === "23505") throw new ShiftConflictError("Ya tienes una bitácora abierta."); if (created.error || !created.data) throw new Error("No se pudo abrir la bitácora"); const notification = await recordNotification(created.data, profile.rp_name, "open"); return { shift: created.data, notification }; }
export async function closeShift() { const profile = await requireActiveProfile(); const client = createSupabaseAdminClient(); const closed = await client.from("ems_shifts").update({ ended_at: new Date().toISOString() }).eq("profile_id", profile.id).is("ended_at", null).select("*").maybeSingle<Shift>(); if (closed.error || !closed.data) throw new ShiftConflictError("No tienes una bitácora abierta."); const notification = await recordNotification(closed.data, profile.rp_name, "close"); return { shift: closed.data, notification, duration: formatDuration(shiftDurationMilliseconds(closed.data.started_at, closed.data.ended_at!)) }; }

export async function webhookStatus(profileId: string) { await requireAdmin(); const result = await createSupabaseAdminClient().from("ems_discord_webhooks").select("profile_id").eq("profile_id", profileId).maybeSingle(); return { configured: Boolean(result.data) }; }
export async function webhookStatuses() { await requireAdmin(); const result = await createSupabaseAdminClient().from("ems_discord_webhooks").select("profile_id"); return new Set((result.data ?? []).map((item) => item.profile_id as string)); }
function validateWebhook(value: unknown) { if (typeof value !== "string" || !isDiscordWebhookUrl(value.trim())) throw new WebhookConfigurationError("La URL debe ser un webhook válido de Discord."); return value.trim(); }
export async function saveWebhook(profileId: string, value: unknown) { await requireAdmin(); const webhook = validateWebhook(value); let key: string; try { key = getWebhookEncryptionKey().toString("base64"); } catch { throw new WebhookConfigurationError("Falta configurar EMS_WEBHOOK_ENCRYPTION_KEY en el servidor."); } const encrypted = encryptWebhook(webhook, key); const result = await createSupabaseAdminClient().from("ems_discord_webhooks").upsert({ profile_id: profileId, ...encrypted, updated_at: new Date().toISOString() }); if (result.error) throw new Error("No se pudo guardar la configuración de Discord"); return { configured: true }; }
export async function deleteWebhook(profileId: string) { await requireAdmin(); const result = await createSupabaseAdminClient().from("ems_discord_webhooks").delete().eq("profile_id", profileId); if (result.error) throw new Error("No se pudo eliminar la configuración de Discord"); return { configured: false }; }
export async function testWebhook(profileId: string, value: unknown) { const admin = await requireAdmin(); const webhook = validateWebhook(value); const profile = await createSupabaseAdminClient().from("profiles").select("rp_name").eq("id", profileId).maybeSingle<{ rp_name: string }>(); if (!profile.data) throw new Error("EMS no encontrado"); try { await sendDiscordWebhook({ webhookUrl: webhook, content: `✅ Webhook de bitácora configurado correctamente para ${profile.data.rp_name}.`, attachments: [] }); return { message: "Webhook probado correctamente." }; } catch (error) { throw new Error(safeError(error).includes("timeout") ? "Discord no respondió a tiempo." : "Discord rechazó el webhook o no se pudo conectar."); } finally { void admin; } }
