"use client";

import { useState } from "react";
import { ChoiceDialog } from "@/components/ui/choice-dialog";
import { useToast } from "@/components/feedback/toast-provider";
import { conversionNotice } from "@/lib/staff-control/presentation";
import type { listStaff } from "@/server/staff-control";

type Staff = Awaited<ReturnType<typeof listStaff>>["items"][number]; type Type = "warn" | "strike" | "fine";
const monday = () => { const now = new Date(); const offset = (now.getDay() + 6) % 7; now.setDate(now.getDate() - offset); return now.toISOString().slice(0, 10); };
export function SanctionDialog({ open, initialStaff, staff, onClose, onSaved }: { open: boolean; initialStaff: Staff | null; staff: Staff[]; onClose: () => void; onSaved: () => void }) {
  const toast = useToast(); const [selected, setSelected] = useState<Staff | null>(initialStaff); const [type, setType] = useState<Type>("warn"); const [reason, setReason] = useState(""); const [amount, setAmount] = useState(""); const [week, setWeek] = useState(monday()); const [preview, setPreview] = useState<{ willGenerateStrike: boolean; activeWarnsBefore: number; activeWarnsAfterOrConversion: number; warnsPerStrike: number } | null>(null); const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  if (!open) return null;
  async function review() { if (!selected || !reason.trim() || type === "fine" && (!/^\d+$/.test(amount) || Number(amount) <= 0)) { setError("Completa los campos obligatorios."); return; } setBusy(true); setError(""); try { const response = await fetch(`/api/admin/staff/actions?profileId=${selected.profile.id}&type=${type}`); if (!response.ok) throw new Error((await response.json()).error); const next = await response.json(); setPreview(next); setConfirm(true); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo preparar la sanción."); } finally { setBusy(false); } }
  async function submit() { if (!selected) return; setBusy(true); try { const response = await fetch("/api/admin/staff/actions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profileId: selected.profile.id, type, reason, fineAmount: type === "fine" ? Number(amount) : undefined, appliesToWeek: type === "fine" ? week : undefined }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); toast.success(type === "warn" && result.generatedStrikeId ? "Warn aplicado. 3 warns se convirtieron en 1 strike." : type === "strike" && result.nowCritical ? "Strike aplicado. El EMS ahora requiere revisión administrativa." : type === "fine" ? "Multa registrada correctamente." : "Warn aplicado correctamente."); onSaved(); onClose(); } catch (cause) { setConfirm(false); setError(cause instanceof Error ? cause.message : "No se pudo aplicar la sanción."); } finally { setBusy(false); } }
  return <><div className="staff-dialog-overlay" role="presentation"><section aria-labelledby="sanction-title" aria-modal="true" className="staff-dialog glass-card" role="dialog"><div className="flex items-center justify-between gap-3"><h2 id="sanction-title">Registrar sanción</h2><button aria-label="Cerrar" className="button button-ghost" type="button" onClick={onClose}>Cerrar</button></div><div className="staff-form">{!initialStaff && <label className="field">EMS<select className="field-input" value={selected?.profile.id ?? ""} onChange={(event) => setSelected(staff.find((item) => item.profile.id === event.target.value) ?? null)}><option value="">Selecciona personal</option>{staff.map((item) => <option key={item.profile.id} value={item.profile.id}>{item.profile.rpName}</option>)}</select></label>}<label className="field">Tipo<select className="field-input" value={type} onChange={(event) => { setType(event.target.value as Type); setPreview(null); }}><option value="warn">Warn</option><option value="strike">Strike</option><option value="fine">Multa</option></select></label><label className="field">Motivo<textarea className="field-input" value={reason} onChange={(event) => setReason(event.target.value)} required rows={3} /></label>{type === "fine" && <div className="grid gap-3 sm:grid-cols-2"><label className="field">Monto (pesos)<input className="field-input" inputMode="numeric" min="1" type="number" value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label className="field">Semana afectada<input className="field-input" type="date" value={week} onChange={(event) => setWeek(event.target.value)} /></label></div>}{error && <p className="form-error" role="alert">{error}</p>}<button aria-busy={busy} className="button button-danger" disabled={busy} type="button" onClick={review}>{busy ? "Preparando…" : "Revisar sanción"}</button></div></section></div><ChoiceDialog open={confirm} title="Aplicar sanción" description={`${selected?.profile.rpName ?? "EMS"} · ${type === "warn" ? "Warn" : type === "strike" ? "Strike" : "Multa"}`} details={`${reason}${type === "fine" ? `\n\nMonto: $${Number(amount).toLocaleString("es-MX")} · Semana: ${week}` : type === "warn" && preview ? `\n\n${conversionNotice(preview)}` : ""}`} onClose={() => setConfirm(false)} onSelect={(key) => key === "confirm" ? submit() : setConfirm(false)} options={[{ key: "cancel", label: "Cancelar", tone: "secondary" }, { key: "confirm", label: busy ? "Aplicando…" : "Aplicar sanción", tone: "danger" }]} /></>;
}
