"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { EmptyState } from "@/components/ui";
import { emptyStaffState, staffSearchParams, summaryFilter, type StaffFilter } from "@/lib/staff-control/presentation";
import type { listStaff } from "@/server/staff-control";
import { AttentionQueue } from "./attention-queue";
import { SanctionDialog } from "./sanction-dialog";
import { StaffCard } from "./staff-card";
import { StaffFilters } from "./staff-filters";

type Data = Awaited<ReturnType<typeof listStaff>>; type Staff = Data["items"][number];
export function StaffCenter({ data, query, filter }: { data: Data; query: string; filter: StaffFilter }) { const router = useRouter(); const params = useSearchParams(); const [sanctionTarget, setSanctionTarget] = useState<Staff | null>(null); const [dialog, setDialog] = useState(false); const summary: Array<{ key: StaffFilter; label: string; value: number }> = [{ key: "all", label: "Activos", value: data.summary.active }, { key: "attention", label: "Atención", value: data.summary.attention }, { key: "critical", label: "Críticos", value: data.summary.critical }, { key: "goal", label: "No cumplen meta", value: data.summary.goalMissed }, { key: "inactive", label: "Inactivos", value: data.summary.inactive }]; const attention = data.items.filter((item) => item.status.key !== "normal"); const empty = emptyStaffState(query); const go = (key: StaffFilter) => router.push(`?${staffSearchParams(params, { filter: summaryFilter(key) })}`);
  return <><div className="staff-summary" aria-label="Resumen de personal">{summary.map((item) => <button aria-current={filter === item.key ? "true" : undefined} className={`staff-summary-card ${filter === item.key ? "selected" : ""}`} key={item.label} type="button" onClick={() => go(item.key)}><strong>{item.value}</strong><span>{item.label}</span></button>)}</div><div className="staff-primary-layout"><AttentionQueue items={attention} onSanction={(staff) => { setSanctionTarget(staff); setDialog(true); }} /><aside className="staff-weekly-note"><p className="eyebrow">Esta semana</p><h2>Qué revisar</h2><p>Prioriza críticos, meta no cumplida y actividad pendiente antes del cierre semanal.</p></aside></div><StaffFilters initialFilter={filter} initialQuery={query} /><section aria-labelledby="staff-list-title"><div className="staff-list-heading"><div><p className="eyebrow">Equipo operativo</p><h2 id="staff-list-title">Personal completo</h2></div><p>{data.total} EMS</p></div>{data.items.length ? <div className="staff-grid">{data.items.map((staff) => <StaffCard key={staff.profile.id} staff={staff} onSanction={(target) => { setSanctionTarget(target); setDialog(true); }} />)}</div> : <EmptyState title={empty.title} description={empty.description} icon="users" />}{data.totalPages > 1 && <nav className="staff-pagination" aria-label="Paginación de personal"><button className="button button-secondary" disabled={data.page === 1} type="button" onClick={() => router.push(`?${staffSearchParams(params, { page: data.page - 1 })}`)}>Anterior</button><span>Página {data.page} de {data.totalPages}</span><button className="button button-secondary" disabled={data.page === data.totalPages} type="button" onClick={() => router.push(`?${staffSearchParams(params, { page: data.page + 1 })}`)}>Siguiente</button></nav>}</section><button className="button button-primary staff-global-cta" type="button" onClick={() => { setSanctionTarget(null); setDialog(true); }}>Registrar sanción</button><SanctionDialog key={`${dialog}-${sanctionTarget?.profile.id ?? "global"}`} initialStaff={sanctionTarget} open={dialog} staff={data.items} onClose={() => setDialog(false)} onSaved={() => router.refresh()} /></>; }
