"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, type TooltipContentProps } from "recharts";

import { Card } from "@/components/ui";
import type { AdminAnalytics, AnalyticsPeriod, AnalyticsProfile, DailyAnalytics } from "@/lib/analytics/aggregation";

const periodOptions: Array<[AnalyticsPeriod, string]> = [["week", "Esta semana"], ["previous-week", "Semana anterior"], ["7d", "Últimos 7 días"], ["30d", "Últimos 30 días"]];
const labels: Record<string, string> = { workedMinutes: "Horas totales", peakMinutes: "Horario fuerte", normalMinutes: "Horario normal", activeProfiles: "EMS con actividad", shifts: "Turnos", deliveries: "Entregas", civilDeliveries: "Entregas civiles", policeDeliveries: "Entregas policiales" };
const colors = { peak: "#60a5fa", normal: "#64748b", civil: "#34d399", police: "#c084fc" };

function minutes(value: number) { return `${Math.floor(value / 60)}h ${String(value % 60).padStart(2, "0")}m`; }
function shortMinutes(value: number) { return value >= 60 ? `${Math.round(value / 60)}h` : `${value}m`; }
function pesos(value: number) { return new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN", maximumFractionDigits: 0 }).format(value); }
function number(value: unknown) { return typeof value === "number" ? value : Number(value ?? 0); }
function compareLabel(value: { label: string; value: number | null }) { return value.value === 0 ? "Sin cambio" : value.label; }
function selectedDaily(data: AdminAnalytics, profile: AnalyticsProfile | null): DailyAnalytics[] { return profile?.daily ?? data.daily; }
function selectedDeliveries(data: AdminAnalytics, profile: AnalyticsProfile | null) { return profile ? { civil: profile.civilDeliveries, police: profile.policeDeliveries, total: profile.deliveries, civilPercentage: profile.deliveries ? Math.round((profile.civilDeliveries / profile.deliveries) * 100) : 0, policePercentage: profile.deliveries ? Math.round((profile.policeDeliveries / profile.deliveries) * 100) : 0 } : data.deliveries.byType; }

function ChartTooltip({ active, payload, label, formatValue = (value) => String(value) }: Partial<TooltipContentProps<number, string>> & { formatValue?: (value: number, dataKey: string) => string }) {
  if (!active || !payload?.length) return null;
  return <div className="analytics-tooltip"><strong>{label}</strong>{payload.map((entry) => <div className="analytics-tooltip-row" key={String(entry.dataKey)}><span style={{ color: entry.color }}>{labels[String(entry.dataKey)] ?? entry.name}</span><b>{formatValue(number(entry.value), String(entry.dataKey))}</b></div>)}</div>;
}

function Comparison({ value }: { value: { label: string; value: number | null } }) { return <span className={`analytics-comparison ${value.value !== null && value.value < 0 ? "negative" : "positive"}`}>{compareLabel(value)} vs periodo anterior</span>; }
function Kpi({ label, value, comparison }: { label: string; value: string | number; comparison?: { label: string; value: number | null } }) { return <div className="analytics-kpi"><span>{label}</span><strong>{value}</strong>{comparison && <Comparison value={comparison} />}</div>; }
function Section({ title, eyebrow, children, className = "" }: { title: string; eyebrow?: string; children: React.ReactNode; className?: string }) { return <Card className={`analytics-card ${className}`}><div className="analytics-card-heading">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2></div>{children}</Card>; }
function EmptyChart({ text }: { text: string }) { return <div className="analytics-empty-chart" role="status">{text}</div>; }

export function AnalyticsCenter({ data }: { data: AdminAnalytics }) {
  const router = useRouter();
  const [profileId, setProfileId] = useState("");
  const [metric, setMetric] = useState<"hours" | "peak" | "deliveries" | "shifts" | "days">("hours");
  const [pending, startTransition] = useTransition();
  const selected = data.profiles.find((profile) => profile.profileId === profileId) ?? null;
  const daily = selectedDaily(data, selected);
  const deliveryType = selectedDeliveries(data, selected);
  const profileMetrics = selected ? { workedMinutes: selected.totalMinutes, peakMinutes: selected.peakMinutes, shifts: selected.shifts, deliveries: selected.deliveries, activityProfiles: selected.totalMinutes > 0 || selected.deliveries > 0 ? 1 : 0 } : data.kpis;
  const ranking = (selected ? [selected] : data.ranking).map((profile) => ({ name: profile.rpName, value: metric === "hours" ? profile.totalMinutes : metric === "peak" ? profile.peakMinutes : metric === "deliveries" ? profile.deliveries : metric === "shifts" ? profile.shifts : profile.activeDays, metric })).sort((left, right) => right.value - left.value || left.name.localeCompare(right.name));
  const peakNormal = selected ? [{ profileId: selected.profileId, name: selected.rpName, peakMinutes: selected.peakMinutes, normalMinutes: selected.normalMinutes }] : data.peakNormal.byProfile;
  const discipline = selected ? selected.discipline : data.discipline;
  const currentTeam = selected ? (selected.openShift ? [{ profileId: selected.profileId, name: selected.rpName, durationMinutes: selected.openShift.durationMinutes }] : []) : data.currentTeam;
  const latestActivity = selected ? [{ profileId: selected.profileId, name: selected.rpName, lastActivityAt: selected.lastActivityAt, inactivityDays: selected.inactivityDays, inactivityLabel: selected.inactivityLabel }] : data.lastActivity;
  const metricFormat = metric === "hours" || metric === "peak" ? shortMinutes : (value: number) => String(value);
  const pieData = [{ name: "Ciudadanos", value: deliveryType.civil, color: colors.civil }, { name: "Policías", value: deliveryType.police, color: colors.police }].filter((item) => item.value > 0);

  function changePeriod(value: string) { startTransition(() => router.push(`/admin/analytics?period=${encodeURIComponent(value)}`)); }

  return <div className="analytics-page" aria-busy={pending}>
    <div className="analytics-toolbar">
      <label className="analytics-select"><span>Periodo</span><select id="analytics-period" name="period" value={data.period.key} onChange={(event) => changePeriod(event.target.value)}><option value="week">Esta semana</option>{periodOptions.slice(1).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label className="analytics-select"><span>EMS</span><select id="analytics-profile" name="profileId" value={profileId} onChange={(event) => setProfileId(event.target.value)}><option value="">Todos</option>{data.profiles.map((profile) => <option key={profile.profileId} value={profile.profileId}>{profile.rpName}</option>)}</select></label>
      <p className="analytics-range">{data.period.label} · {new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeZone: data.period.timeZone }).format(new Date(data.period.start))} — {new Intl.DateTimeFormat("es-MX", { dateStyle: "medium", timeZone: data.period.timeZone }).format(new Date(data.period.end))}</p>
    </div>
    <section className="analytics-kpi-grid" aria-label="Resumen del periodo">
      <Kpi label="Horas trabajadas" value={minutes(profileMetrics.workedMinutes)} comparison={selected ? undefined : data.comparison.workedMinutes} />
      <Kpi label="Horario fuerte" value={minutes(selected ? selected.peakMinutes : data.kpis.peakMinutes)} comparison={selected ? undefined : data.comparison.peakMinutes} />
      <Kpi label="Turnos" value={profileMetrics.shifts} comparison={selected ? undefined : data.comparison.shifts} />
      <Kpi label="Entregas" value={profileMetrics.deliveries} comparison={selected ? undefined : data.comparison.deliveries} />
      <Kpi label={selected ? "Días activos" : "EMS con actividad"} value={selected ? selected.activeDays : `${profileMetrics.activityProfiles} de ${data.kpis.activeProfiles}`} comparison={selected ? undefined : data.comparison.activityProfiles} />
      <Kpi label="Requieren atención" value={selected ? (selected.status.key === "normal" ? 0 : 1) : data.kpis.attention} />
    </section>
    <Section title={selected ? `Actividad de ${selected.rpName}` : "Actividad del hospital"} eyebrow="Rendimiento del periodo" className="analytics-wide">
      <div className="analytics-chart analytics-main-chart">{daily.some((item) => item.workedMinutes > 0) ? <ResponsiveContainer width="100%" height={300}><AreaChart data={daily} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="rgba(148,163,184,.12)" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#94a3b8", fontSize: 11 }} tickLine={false} axisLine={false} /><YAxis yAxisId="minutes" tickFormatter={shortMinutes} tick={{ fill: "#94a3b8", fontSize: 11 }} tickLine={false} axisLine={false} width={42} /><YAxis yAxisId="activity" hide domain={[0, "auto"]} /><Tooltip content={<ChartTooltip formatValue={(value, key) => key === "activeProfiles" ? String(value) : minutes(value)} />} /><Legend /><Area yAxisId="minutes" name="Horas totales" dataKey="workedMinutes" type="monotone" stroke="#60a5fa" fill="rgba(96,165,250,.18)" strokeWidth={2} /><Area yAxisId="minutes" name="Horario fuerte" dataKey="peakMinutes" type="monotone" stroke="#34d399" fill="transparent" strokeWidth={2} /><Area yAxisId="minutes" name="Horario normal" dataKey="normalMinutes" type="monotone" stroke="transparent" fill="transparent" legendType="none" /><Line yAxisId="activity" name="EMS con actividad" dataKey="activeProfiles" stroke="transparent" dot={false} legendType="none" /></AreaChart></ResponsiveContainer> : <EmptyChart text="No hay shifts en este periodo." />}</div>
      <p className="analytics-context">Cada día conserva sus horas totales, horario fuerte, horario normal y EMS con actividad.</p>
    </Section>
    <div className="analytics-two-columns">
      <Section title="Horas por EMS" eyebrow="Ranking"><div className="analytics-metric-tabs" role="group" aria-label="Métrica del ranking">{([["hours", "Horas"], ["peak", "Horas pico"], ["deliveries", "Entregas"], ["shifts", "Turnos"], ["days", "Días activos"]] as const).map(([key, label]) => <button key={key} type="button" className={metric === key ? "active" : ""} aria-pressed={metric === key} onClick={() => setMetric(key)}>{label}</button>)}</div><div className="analytics-chart analytics-ranking-chart"><ResponsiveContainer width="100%" height={Math.max(220, ranking.length * 34)}><BarChart layout="vertical" data={ranking} margin={{ top: 8, right: 12, left: 4, bottom: 0 }}><XAxis type="number" tickFormatter={metricFormat} tick={{ fill: "#94a3b8", fontSize: 11 }} tickLine={false} axisLine={false} /><YAxis type="category" dataKey="name" width={84} tick={{ fill: "#e2e8f0", fontSize: 11 }} tickLine={false} axisLine={false} /><Tooltip content={<ChartTooltip formatValue={metricFormat} />} /><Bar dataKey="value" name={metric === "hours" ? "Horas trabajadas" : metric === "peak" ? "Horas pico" : metric === "deliveries" ? "Entregas" : metric === "shifts" ? "Turnos" : "Días activos"} fill="#60a5fa" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></div></Section>
      <Section title="Horario fuerte vs normal" eyebrow="Distribución del tiempo"><div className="analytics-chart"><ResponsiveContainer width="100%" height={Math.max(220, peakNormal.length * 34)}><BarChart layout="vertical" data={peakNormal} margin={{ top: 8, right: 12, left: 4, bottom: 0 }}><XAxis type="number" tickFormatter={shortMinutes} tick={{ fill: "#94a3b8", fontSize: 11 }} tickLine={false} axisLine={false} /><YAxis type="category" dataKey="name" width={84} tick={{ fill: "#e2e8f0", fontSize: 11 }} tickLine={false} axisLine={false} /><Tooltip content={<ChartTooltip formatValue={minutes} />} /><Legend /><Bar dataKey="peakMinutes" name="Horario fuerte" stackId="time" fill={colors.peak} radius={[5, 0, 0, 5]} /><Bar dataKey="normalMinutes" name="Horario normal" stackId="time" fill={colors.normal} radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div></Section>
      <Section title="Entregas por día" eyebrow="Actividad registrada"><div className="analytics-chart"><ResponsiveContainer width="100%" height={250}><BarChart data={daily} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="rgba(148,163,184,.12)" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#94a3b8", fontSize: 11 }} tickLine={false} axisLine={false} /><YAxis allowDecimals={false} tick={{ fill: "#94a3b8", fontSize: 11 }} tickLine={false} axisLine={false} width={28} /><Tooltip content={<ChartTooltip />} /><Legend /><Bar dataKey="civilDeliveries" name="Civil" stackId="deliveries" fill={colors.civil} radius={[5, 5, 0, 0]} /><Bar dataKey="policeDeliveries" name="Policía" stackId="deliveries" fill={colors.police} radius={[0, 0, 5, 5]} /></BarChart></ResponsiveContainer></div></Section>
      <Section title="Entregas por tipo" eyebrow="Composición"><div className="analytics-donut-layout">{pieData.length ? <><div className="analytics-chart analytics-donut"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius={54} outerRadius={78} paddingAngle={4}>{pieData.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip content={<ChartTooltip />} /></PieChart></ResponsiveContainer></div><div className="analytics-donut-stats"><p>{selected ? (deliveryType.total ? `${deliveryType.civilPercentage}% de las entregas de ${selected.rpName} fueron civiles.` : "No hubo entregas durante este periodo.") : data.deliveries.insight}</p><div><span><i style={{ background: colors.civil }} />Ciudadanos</span><strong>{deliveryType.civil} · {deliveryType.civilPercentage}%</strong></div><div><span><i style={{ background: colors.police }} />Policías</span><strong>{deliveryType.police} · {deliveryType.policePercentage}%</strong></div><div className="analytics-total"><span>Total de entregas</span><strong>{deliveryType.total}</strong></div></div></> : <EmptyChart text="No hubo entregas durante este periodo." />}</div></Section>
    </div>
    <div className="analytics-two-columns"><RecipientCard title="Ciudadanos con más entregas" items={selected?.recipients.citizens ?? data.recipients.citizens} empty="No hubo entregas civiles." /><RecipientCard title="Oficiales con más entregas" items={selected?.recipients.police ?? data.recipients.police} empty="No hubo entregas policiales." police /></div>
    <div className="analytics-two-columns">
      <Section title={selected ? "Estado actual" : "Equipo ahora"} eyebrow="Operación"><div className="analytics-list">{currentTeam.length ? currentTeam.map((item) => <div className="analytics-list-row" key={item.profileId}><div><strong>{item.name}</strong><span>En turno</span></div><b>{minutes(item.durationMinutes)}</b></div>) : <EmptyChart text={selected ? "Este EMS no está en turno ahora." : "Ningún EMS está en turno ahora."} />}</div><div className="analytics-subsection"><h3>Última actividad</h3>{latestActivity.map((item) => <div className="analytics-list-row" key={item.profileId}><div><strong>{item.name}</strong><span>{item.inactivityLabel}</span></div><b>{item.lastActivityAt ? new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(item.lastActivityAt)) : "Sin registro"}</b></div>)}</div></Section>
      <Section title="Requieren atención" eyebrow="Seguimiento"><div className="analytics-list">{selected ? selected.status.key === "normal" ? <EmptyChart text="Este EMS está en estado normal." /> : <AttentionRow profile={selected} /> : data.attention.length ? data.attention.map((item) => <div className="analytics-list-row" key={item.profileId}><div><strong>{item.name}</strong><span>{item.status} · {item.reason}</span></div><a href={item.href}>Ver expediente</a></div>) : <EmptyChart text="Todo el equipo está en estado normal." />}</div></Section>
      <Section title="Disciplina del periodo" eyebrow="Registro"><div className="analytics-discipline-grid"><Metric label="Warns emitidos" value={discipline.warns} /><Metric label="Strikes emitidos" value={discipline.strikes} /><Metric label="Multas" value={discipline.fines} /><Metric label="Multas aplicadas" value={pesos(discipline.fineTotal)} /><Metric label="Permisos registrados" value={discipline.permissions} /></div></Section>
      <BonusCard bonus={selected?.bonus ?? data.bonus} />
    </div>
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function RecipientCard({ title, items, empty, police = false }: { title: string; items: Array<{ name: string; count: number; percentage: number; badgeNumber: string | null }>; empty: string; police?: boolean }) { return <Section title={title} eyebrow="Personas atendidas"><div className="analytics-recipient-list">{items.length ? items.map((item, index) => <div className="analytics-recipient-row" key={`${item.name}-${item.badgeNumber ?? index}`}><span className="analytics-rank">{index + 1}</span><div><strong>{item.name}</strong>{police && item.badgeNumber && <small>Placa {item.badgeNumber}</small>}</div><b>{item.count} {item.count === 1 ? "entrega" : "entregas"}</b></div>) : <EmptyChart text={empty} />}</div></Section>; }
function AttentionRow({ profile }: { profile: AnalyticsProfile }) { return <div className="analytics-list-row"><div><strong>{profile.rpName}</strong><span>{profile.status.label} · {profile.status.reason}</span></div><a href={`/admin/staff/${profile.profileId}`}>Ver expediente</a></div>; }
function BonusCard({ bonus }: { bonus: AdminAnalytics["bonus"] | AnalyticsProfile["bonus"] }) { return <Section title="Bonos" eyebrow="Resultado guardado"><p className="analytics-bonus-label">Última semana finalizada{bonus ? ` · ${bonus.weekStart}` : ""}</p>{bonus ? <><div className="analytics-bonus-summary"><Metric label="Bono total" value={pesos(bonus.totalAmount)} /><Metric label="Score promedio" value={bonus.averageScore.toFixed(1)} /><Metric label="Overrides" value={bonus.overrides} /><Metric label="Multas descontadas" value={pesos(bonus.fineTotal)} /></div><div className="analytics-top3">{bonus.top3.map((item, index) => <div key={item.profileId}><span>#{index + 1}</span><strong>{item.name}</strong><b>{item.score}</b></div>)}</div>{"score" in bonus && <p className="analytics-bonus-breakdown">Score {bonus.score} · Peak {bonus.components.peak} · Kits {bonus.components.kits} · Normal {bonus.components.normal} · Consistency {bonus.components.consistency} · {pesos(bonus.amount)}</p>}</> : <EmptyChart text="No hay una semana finalizada disponible." />}</Section>; }
