export type DniBox = { x0: number; y0: number; x1: number; y1: number };
export type DniWord = { text: string; confidence?: number; bbox: DniBox; blockNum?: number; paragraphNum?: number; lineNum?: number; wordNum?: number };
export type DniRow = { index: number; words: DniWord[]; bbox: DniBox; centerY: number; height: number };
export type DniLabel = "surname" | "firstName" | "birthDate" | "sex" | "nationality" | "document";
export type DniAnchor = { label: DniLabel; word: DniWord; row: DniRow };
export type DniField = "surname" | "firstName";
export type DniCandidate = { text: string; confidence: number; geometry: number; repetitions: number; source?: "tokens" | "regional"; pass?: string };
export type DniScoreDebug = { candidate: string; confidence: number; geometry: number; repetitions: number; validText: boolean; geometryContribution: number; confidenceContribution: number; repetitionContribution: number; lengthBonus: number; invalidPenalty: number; score: number; threshold: number; accepted: boolean; rejectionReason?: string };
export type ScoredDniCandidate = DniCandidate & { score: number; accepted: boolean; scoreDebug?: DniScoreDebug };
export type DniPreprocessInfo = { scale: number; grayscale: boolean; contrast: string };
export type DniImageVariant = { mode: "A" | "B" | "C"; blob: Blob; previewUrl: string; original: { width: number; height: number }; processed: { width: number; height: number }; preprocess: DniPreprocessInfo };
export type DniRegionalPass = { mode: "A" | "B" | "C"; raw: string; confidence: number; candidate?: ScoredDniCandidate; previewUrl: string; input?: { processed: { width: number; height: number }; preprocess: DniPreprocessInfo } };
export type DniTokenRejection = { text: string; reason: string; confidence?: number; bbox: DniBox };
export type DniAnchorCandidate = { text: string; confidence?: number; score: number; reason: string; rowIndex: number; bbox: DniBox };
export type DniAnchorDebug = { label: DniLabel; found: boolean; matchedText?: string; confidence?: number; bbox?: DniBox; rowIndex?: number; matchReason?: string; candidates: DniAnchorCandidate[] };
export type DniFieldDebug = { field: DniField; anchor?: DniAnchor; row?: DniRow; rowTokens: DniWord[]; allRightTokens?: DniWord[]; rejectedTokens?: DniTokenRejection[]; tokenCandidate?: ScoredDniCandidate; rawCandidate?: ScoredDniCandidate; score?: DniScoreDebug; regionalReason?: string; regional?: { region: { x: number; y: number; width: number; height: number }; passes: DniRegionalPass[]; selected?: ScoredDniCandidate }; selected?: ScoredDniCandidate; decision: string };
export type DniRawOutputDiagnostics = {
  resultKeys: string[];
  dataKeys: string[];
  textType: string;
  textLength: number;
  text: string;
  confidence: number | null;
  blocks: { type: string; length: number | null; sampleKeys: string[]; paragraphs: number; lines: number; words: number };
  tsv: { type: string; length: number | null; lines: string[]; text?: string };
  hocr: { type: string; length: number | null; preview: string };
  words: { exists: boolean; type: string; count: number | null; sample: Array<{ text: string; confidence: number | null; bbox?: DniBox }> };
  parsedWordCount: number;
  geometrySource: "words" | "blocks" | "tsv" | "none";
  options: { recognize: Record<string, unknown>; output?: Record<string, boolean> };
  durationMs: number;
};
export type DniWorkerEvent = { status: string; progress: number; elapsedMs: number };
export type DniLanguageDiagnostic = { language: string; text: string; textLength: number; dataKeys: string[]; durationMs: number; error?: string };
export type DniEngineDiagnostics = {
  version: string;
  language: string;
  workerCreated: boolean;
  createDurationMs: number;
  events: DniWorkerEvent[];
  errors: string[];
  parameters: Array<{ mode: string; values: Record<string, unknown> }>;
  cache: { langPath: string; cachePath: string; cacheMethod: string; workerBlobURL: string };
  tests?: { A: DniRawOutputDiagnostics; B: DniRawOutputDiagnostics; C: DniRawOutputDiagnostics };
  languageComparison?: DniLanguageDiagnostic;
};
export type DniPipelineEvent = { atMs: number; message: string; details?: string };
export type DniTechnicalError = { name: string; message: string; stack?: string };
export type DniPassDiagnostic = { raw: DniRawOutputDiagnostics; input: DniImageVariant; language: string; psm: string; wordCount: number; rowCount: number; anchorCount: number; durationMs: number };
export type DniPassDebug = { mode: "A" | "B" | "C"; raw: string; confidence: number; variant: DniImageVariant; rows: DniRow[]; anchors: Partial<Record<DniLabel, DniAnchor>>; anchorDiagnostics?: Partial<Record<DniLabel, DniAnchorDebug>>; fields: Partial<Record<DniField, DniFieldDebug>>; durationMs: number; diagnostic?: DniPassDiagnostic };
export type DniV2Debug = { fileName?: string; passes: DniPassDebug[]; fields: Partial<Record<DniField, DniFieldDebug>>; strategy: string; durationMs: number; status?: "SUCCESS" | "PARTIAL" | "FAILED"; failureReason?: string; error?: DniTechnicalError; pipelineLog?: DniPipelineEvent[]; engine?: DniEngineDiagnostics };
export type DniV2Fields = { firstName: string; lastName: string; status: "detected" | "partial" | "empty"; confidence: "high" | "medium" | "low"; firstNameConfidence: number; lastNameConfidence: number; strategy: string };
export type DniV2Result = { fields: DniV2Fields; debug: DniV2Debug };
