"use client";

import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { SearchField } from "@/components/ui";
import { useToast } from "@/components/feedback/toast-provider";
import { categoryOptions, filterPrices, searchPrices, type PriceCatalogItem } from "@/lib/prices/catalog";
import { formatPesos } from "@/lib/staff-control/bonus";

type FormState = { name: string; category: string; price: string; unit: string; description: string; sortOrder: string; active: boolean };
type DialogState = { item: PriceCatalogItem | null; form: FormState } | null;
type ActiveFilter = "active" | "inactive" | "all";

const emptyForm = (): FormState => ({ name: "", category: "Servicios", price: "", unit: "", description: "", sortOrder: "0", active: true });
const formFor = (item: PriceCatalogItem): FormState => ({ name: item.name, category: item.category, price: String(item.price), unit: item.unit ?? "", description: item.description ?? "", sortOrder: String(item.sortOrder), active: item.active });

function PriceFormDialog({ state, busy, onChange, onClose, onSubmit }: { state: DialogState; busy: boolean; onChange: (form: FormState) => void; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const nameRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (!state) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) onClose(); }; window.addEventListener("keydown", close); const timer = window.setTimeout(() => nameRef.current?.focus(), 0); return () => { window.clearTimeout(timer); window.removeEventListener("keydown", close); }; }, [busy, onClose, state]);
  if (!state) return null;
  const { form, item } = state;
  return <div className="price-dialog-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="price-dialog glass-card" role="dialog" aria-modal="true" aria-labelledby="price-dialog-title"><div className="price-dialog-head"><div><p className="eyebrow">Catálogo EMS</p><h2 id="price-dialog-title">{item ? "Editar precio" : "Agregar precio"}</h2></div><button className="button button-ghost" type="button" onClick={onClose} disabled={busy}>Cerrar</button></div><form className="price-form" onSubmit={onSubmit}><label className="field">Nombre<input ref={nameRef} className="field-input" type="text" required maxLength={120} value={form.name} onChange={(event) => onChange({ ...form, name: event.target.value })} /></label><label className="field">Categoría<input className="field-input" type="text" required maxLength={80} value={form.category} onChange={(event) => onChange({ ...form, category: event.target.value })} /></label><div className="price-form-grid"><label className="field">Precio<input className="field-input" type="number" min={0} step={1} inputMode="numeric" required value={form.price} onChange={(event) => onChange({ ...form, price: event.target.value })} /></label><label className="field">Unidad <span className="price-optional">opcional</span><input className="field-input" type="text" maxLength={40} placeholder="c/u" value={form.unit} onChange={(event) => onChange({ ...form, unit: event.target.value })} /></label></div><label className="field">Descripción <span className="price-optional">opcional</span><textarea className="field-input" rows={3} maxLength={500} value={form.description} onChange={(event) => onChange({ ...form, description: event.target.value })} /></label><label className="field">Orden <span className="price-optional">menor primero</span><input className="field-input" type="number" min={0} step={1} inputMode="numeric" value={form.sortOrder} onChange={(event) => onChange({ ...form, sortOrder: event.target.value })} /></label>{!item && <label className="price-checkbox"><input type="checkbox" checked={form.active} onChange={(event) => onChange({ ...form, active: event.target.checked })} /> Activo</label>}<div className="price-dialog-actions"><button className="button button-ghost" type="button" onClick={onClose} disabled={busy}>Cancelar</button><button className="button button-primary" type="submit" disabled={busy}>{busy ? "Guardando…" : item ? "Guardar cambios" : "Agregar precio"}</button></div></form></section></div>;
}

export function PriceCatalog({ initialPrices, isAdmin }: { initialPrices: PriceCatalogItem[]; isAdmin: boolean }) {
  const router = useRouter();
  const toast = useToast();
  const [items, setItems] = useState(initialPrices);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [active, setActive] = useState<ActiveFilter>("active");
  const [dialog, setDialog] = useState<DialogState>(null);
  const [busy, setBusy] = useState(false);
  const categories = useMemo(() => categoryOptions(items), [items]);
  const visible = useMemo(() => filterPrices(searchPrices(items, query), { active: isAdmin ? active : "active", category }), [active, category, isAdmin, items, query]);

  function refreshItems(saved: PriceCatalogItem) { setItems((current) => { const exists = current.some((item) => item.id === saved.id); return exists ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved].sort((left, right) => left.sortOrder - right.sortOrder || left.name.localeCompare(right.name, "es")); }); router.refresh(); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!dialog) return; setBusy(true); try { const payload = { name: dialog.form.name, category: dialog.form.category, price: Number(dialog.form.price), unit: dialog.form.unit, description: dialog.form.description, sortOrder: Number(dialog.form.sortOrder), ...(dialog.item ? {} : { active: dialog.form.active }) }; const response = await fetch(dialog.item ? `/api/prices/${dialog.item.id}` : "/api/prices", { method: dialog.item ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.price) throw new Error(body?.error ?? "No se pudo guardar el precio."); refreshItems(body.price as PriceCatalogItem); setDialog(null); toast.success(dialog.item ? "Precio actualizado." : "Precio agregado."); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "No se pudo guardar el precio."); } finally { setBusy(false); } }
  async function toggle(item: PriceCatalogItem) { setBusy(true); try { const response = await fetch(`/api/prices/${item.id}/active`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !item.active }) }); const body = await response.json().catch(() => null); if (!response.ok || !body?.price) throw new Error(body?.error ?? "No se pudo actualizar el estado."); refreshItems(body.price as PriceCatalogItem); toast.success(item.active ? "Precio desactivado." : "Precio reactivado."); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "No se pudo actualizar el estado."); } finally { setBusy(false); } }

  return <section className="price-catalog"><div className="price-toolbar"><SearchField aria-label="Buscar servicio o producto" placeholder="Buscar servicio o producto…" value={query} onChange={(event) => setQuery(event.target.value)} />{isAdmin && <button className="button button-primary" type="button" onClick={() => setDialog({ item: null, form: emptyForm() })}>+ Agregar precio</button>}</div>{isAdmin && <div className="price-view-filters" role="group" aria-label="Estado de precios">{([ ["active", "Activos"], ["inactive", "Inactivos"], ["all", "Todos"] ] as const).map(([key, label]) => <button className={`price-filter ${active === key ? "active" : ""}`} aria-pressed={active === key} type="button" key={key} onClick={() => setActive(key)}>{label}</button>)}</div>}<div className="price-category-filters" role="list" aria-label="Categorías de precios"><button className={`price-filter ${category === "all" ? "active" : ""}`} aria-pressed={category === "all"} type="button" onClick={() => setCategory("all")}>Todos</button>{categories.map((option) => <button className={`price-filter ${category === option ? "active" : ""}`} aria-pressed={category === option} type="button" key={option} onClick={() => setCategory(option)}>{option}</button>)}</div>{visible.length ? <div className="price-grid">{visible.map((item) => <article className={`price-card ${item.active ? "" : "price-card-inactive"}`} key={item.id}><div className="price-card-top"><span className="price-category">{item.category}</span>{isAdmin && <span className={`price-status ${item.active ? "price-status-active" : "price-status-inactive"}`}>{item.active ? "Activo" : "Inactivo"}</span>}</div><h2>{item.name}</h2><p className="price-amount">{formatPesos(item.price)}{item.unit && <> <small>{item.unit}</small></>}</p>{item.description && <p className="price-description">{item.description}</p>}{isAdmin && <><p className="price-updated">{item.updatedAt ? `Actualizado ${new Intl.DateTimeFormat("es-MX", { dateStyle: "medium" }).format(new Date(item.updatedAt))}` : "Sin cambios registrados"}</p><div className="price-card-actions"><button className="button button-secondary" type="button" disabled={busy} onClick={() => setDialog({ item, form: formFor(item) })}>Editar</button><button className={`button ${item.active ? "button-ghost" : "button-primary"}`} type="button" disabled={busy} onClick={() => void toggle(item)}>{item.active ? "Desactivar" : "Reactivar"}</button></div></>}</article>)}</div> : <div className="price-empty" role="status">No hay precios que coincidan con la búsqueda.</div>}<PriceFormDialog state={dialog} busy={busy} onChange={(form) => setDialog((current) => current ? { ...current, form } : current)} onClose={() => setDialog(null)} onSubmit={(event) => void submit(event)} /></section>;
}
