"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { PersonRecord } from "@/server/people";
import { globalSearchActions, shouldSearch } from "@/lib/people/global-search";
import { Icon } from "@/components/ui";

export function GlobalSearch({ open, onClose }: { open: boolean; onClose: () => void }) {
  const router = useRouter(); const inputRef = useRef<HTMLInputElement>(null); const sequence = useRef(0); const [query, setQuery] = useState(""); const [items, setItems] = useState<PersonRecord[]>([]); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState(0); const [actionPerson, setActionPerson] = useState<PersonRecord | null>(null);
  useEffect(() => { if (!open) return; inputRef.current?.focus(); const keyboard = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", keyboard); return () => window.removeEventListener("keydown", keyboard); }, [open, onClose]);
  useEffect(() => { if (!shouldSearch(query)) return; const current = ++sequence.current; const controller = new AbortController(); const timer = window.setTimeout(async () => { setLoading(true); try { const response = await fetch(`/api/people?${new URLSearchParams({ search: query, page: "1", pageSize: "6" })}`, { signal: controller.signal }); const data = await response.json() as { items?: PersonRecord[] }; if (!response.ok || !Array.isArray(data.items)) throw new Error(); if (current === sequence.current) { setItems(data.items); setSelected(0); } } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError") && current === sequence.current) setItems([]); } finally { if (current === sequence.current) setLoading(false); } }, 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query]);
  function close() { setQuery(""); setItems([]); setActionPerson(null); onClose(); }
  function choose(person: PersonRecord) { setActionPerson(person); }
  function keyDown(event: React.KeyboardEvent<HTMLInputElement>) { if (event.key === "ArrowDown") { event.preventDefault(); setSelected((value) => Math.min(value + 1, items.length - 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setSelected((value) => Math.max(value - 1, 0)); } if (event.key === "Enter" && items[selected]) { event.preventDefault(); choose(items[selected]); } }
  function navigate(href: string) { close(); router.push(href); }
  if (!open) return null;
  function changeQuery(value: string) { sequence.current += 1; setQuery(value); setActionPerson(null); if (!shouldSearch(value)) { setItems([]); setLoading(false); setSelected(0); } }
  return <div className="global-search-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }}><section className="global-search-dialog" role="dialog" aria-modal="true" aria-labelledby="global-search-title"><div className="flex items-center justify-between gap-3"><h2 id="global-search-title" className="text-lg font-bold">Buscar persona</h2><button className="button button-ghost" type="button" onClick={close}>Cerrar</button></div><label className="search-field mt-4"><Icon name="search" size={18} /><input ref={inputRef} aria-label="Buscar por nombre, apellido o placa" value={query} onChange={(event) => changeQuery(event.target.value)} onKeyDown={keyDown} placeholder="Nombre, apellido o placa" /></label>{!query && <p className="mt-4 text-sm text-[var(--muted)]">Busca por nombre, apellido o placa.</p>}{loading && <div className="mt-4 grid gap-2" aria-live="polite"><div className="skeleton h-14 w-full" /><div className="skeleton h-14 w-full" /></div>}{shouldSearch(query) && !loading && !actionPerson && <div className="mt-4 grid gap-2" role="listbox">{items.map((person, index) => <button className={`global-search-result ${selected === index ? "active" : ""}`} type="button" role="option" aria-selected={selected === index} key={person.id} onMouseEnter={() => setSelected(index)} onClick={() => choose(person)}><span className="min-w-0"><strong className="block truncate">{person.display_name}</strong><span className="mt-1 block text-sm text-[var(--muted)]">{person.type === "police" ? `Policía · Placa: ${person.badge_number ?? "pendiente"}` : "Civil"}</span></span><span>→</span></button>)}{items.length === 0 && <div className="glass-card p-4 text-sm text-[var(--muted)]">{`No encontramos a '${query}'.`}<button className="button button-primary mt-3 w-full" type="button" onClick={() => navigate(`/people/new?searchHint=${encodeURIComponent(query)}`)}>Registrar persona</button></div>}</div>}{actionPerson && <div className="mt-4"><button className="text-sm text-blue-300" type="button" onClick={() => setActionPerson(null)}>← Resultados</button><p className="mt-3 font-semibold">{actionPerson.display_name}</p><div className="mt-3 grid gap-2">{globalSearchActions(actionPerson).map((action) => <button className="button button-secondary w-full" type="button" key={action.href} onClick={() => navigate(action.href)}>{action.label}</button>)}</div></div>}</section></div>;
}
