"use client";

import { useEffect, useState } from "react";
import { useActiveShift } from "@/components/shifts/active-shift-provider";
import { updateActiveShiftAfterMutation } from "@/lib/shifts/active-shift-state";
import { formatDuration, shiftDurationMilliseconds } from "@/lib/shifts/time";
import { useToast } from "@/components/feedback/toast-provider";
import { useConnectivity } from "@/components/feedback/connectivity-provider";

export function ShiftPanel() {
  const { activeShift, loading, setActiveShift } = useActiveShift();
  const toast = useToast(); const { online } = useConnectivity();
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [now, setNow] = useState<number | null>(null);
  useEffect(() => { const refresh = () => setNow(Date.now()); refresh(); const interval = window.setInterval(refresh, 60_000); window.addEventListener("focus", refresh); document.addEventListener("visibilitychange", refresh); return () => { window.clearInterval(interval); window.removeEventListener("focus", refresh); document.removeEventListener("visibilitychange", refresh); }; }, []);
  async function mutate(action: "open" | "close") { if (busy) return; if (!online) { const message = "No hay conexión. Intenta nuevamente cuando recuperes internet."; setNotice(message); toast.error(message); return; } setBusy(true); setNotice(""); try { const response = await fetch(`/api/shifts/${action}`, { method: "POST" }); const body = await response.json() as { shift?: typeof activeShift; notification?: { status?: string; error?: string }; error?: string }; if (!response.ok || !body.shift) throw new Error(body.error ?? "No se pudo actualizar la bitácora"); setActiveShift(updateActiveShiftAfterMutation(activeShift, action, true, body.shift)); setNow(Date.now()); const warning = body.notification?.status === "failed" || body.notification?.status === "not_configured"; const message = warning ? `Bitácora guardada, pero ${body.notification?.error?.toLowerCase() ?? "no se pudo notificar a Discord."}` : action === "open" ? "Bitácora abierta." : "Bitácora cerrada."; setNotice(message); if (warning) toast.info(message); else toast.success(message); } catch (error) { const message = error instanceof Error ? error.message : "No se pudo actualizar la bitácora"; setNotice(message); toast.error(message); } finally { setBusy(false); } }
  if (loading) return <section className="glass-card max-w-xl p-5" aria-label="Cargando bitácora"><div className="h-5 w-24 animate-pulse rounded bg-slate-700/60" /><div className="mt-4 h-9 w-52 animate-pulse rounded bg-slate-700/60" /></section>;
  return <section className="glass-card max-w-xl p-5"><p className="eyebrow">Bitácora</p>{activeShift ? <><div className="mt-3 flex items-center gap-2"><h2 className="text-2xl font-bold">Bitácora abierta</h2><span className="badge badge-success">En servicio</span></div><dl className="mt-6 grid gap-4"><div><dt className="text-sm text-[var(--muted)]">Inicio</dt><dd className="mt-1 font-semibold">{new Intl.DateTimeFormat("es-MX", { timeZone: "America/Monterrey", dateStyle: "short", timeStyle: "short" }).format(new Date(activeShift.started_at))}</dd></div><div><dt className="text-sm text-[var(--muted)]">Tiempo trabajado</dt><dd className="mt-1 text-4xl font-bold">{now === null ? "—" : formatDuration(shiftDurationMilliseconds(activeShift.started_at, new Date(now)))}</dd></div></dl><button className="button button-danger mobile-sticky-cta mt-7 w-full" type="button" aria-busy={busy} disabled={busy} onClick={() => mutate("close")}>{busy ? "Cerrando bitácora…" : "Cerrar bitácora"}</button></> : <><h2 className="mt-3 text-2xl font-bold">Bitácora</h2><p className="mt-3 text-[var(--muted)]">No tienes una bitácora abierta.</p><button className="button button-primary mobile-sticky-cta mt-7 w-full" type="button" aria-busy={busy} disabled={busy} onClick={() => mutate("open")}>{busy ? "Abriendo bitácora…" : "Abrir bitácora"}</button></>}{notice && <p className="mt-4 text-sm text-[var(--muted)]" role="status">{notice}</p>}</section>;
}
