"use client";

import { useEffect, useState } from "react";
import { formatDuration, shiftDurationMilliseconds } from "@/lib/shifts/time";

type Shift = { id: string; started_at: string; ended_at: string | null };
export function ShiftPanel({ initial }: { initial: Shift | null }) {
  const [shift, setShift] = useState(initial); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [now, setNow] = useState<number | null>(null);
  useEffect(() => { const refresh = () => setNow(Date.now()); refresh(); const interval = window.setInterval(refresh, 60000); window.addEventListener("focus", refresh); return () => { window.clearInterval(interval); window.removeEventListener("focus", refresh); }; }, []);
  async function mutate(action: "open" | "close") { setBusy(true); setNotice(""); try { const response = await fetch(`/api/shifts/${action}`, { method: "POST" }); const body = await response.json() as { shift?: Shift; notification?: { status?: string; error?: string }; error?: string }; if (!response.ok || !body.shift) throw new Error(body.error ?? "No se pudo actualizar la bitácora"); setShift(action === "open" ? body.shift : null); setNow(Date.now()); setNotice(body.notification?.status === "failed" || body.notification?.status === "not_configured" ? `Bitácora guardada, pero ${body.notification.error?.toLowerCase() ?? "no se pudo notificar a Discord."}` : action === "open" ? "Bitácora abierta." : "Bitácora cerrada."); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo actualizar la bitácora"); } finally { setBusy(false); } }
  return <section className="glass-card max-w-xl p-6"><p className="eyebrow">Bitácora</p>{shift ? <><div className="mt-3 flex items-center gap-2"><h2 className="text-2xl font-bold">Bitácora abierta</h2><span className="badge badge-success">En servicio</span></div><dl className="mt-6 grid gap-4"><div><dt className="text-sm text-[var(--muted)]">Inicio</dt><dd className="mt-1 font-semibold">{new Intl.DateTimeFormat("es-MX", { timeZone: "America/Monterrey", dateStyle: "short", timeStyle: "short" }).format(new Date(shift.started_at))}</dd></div><div><dt className="text-sm text-[var(--muted)]">Tiempo trabajado</dt><dd className="mt-1 text-3xl font-bold">{now === null ? "—" : formatDuration(shiftDurationMilliseconds(shift.started_at, new Date(now)))}</dd></div></dl><button className="button button-danger mt-7" type="button" disabled={busy} onClick={() => mutate("close")}>{busy ? "Guardando…" : "Cerrar bitácora"}</button></> : <><h2 className="mt-3 text-2xl font-bold">Bitácora</h2><p className="mt-3 text-[var(--muted)]">No tienes una bitácora abierta.</p><button className="button button-primary mt-7" type="button" disabled={busy} onClick={() => mutate("open")}>{busy ? "Guardando…" : "Abrir bitácora"}</button></>}{notice && <p className="mt-4 text-sm text-[var(--muted)]" role="status">{notice}</p>}</section>;
}
